"""Build the (system prompt, message history) tuple fed to each speaker.

Layered context strategy:
  - Topic statement: always present, anchors the conversation.
  - Summary block: compressed digest of older utterances (generated by the
    summarizer, may be empty in early rounds).
  - Sliding window: the last K utterances in full.
  - Pending injections: user-issued /inject commands queued for this speaker.
  - Convergence override: when the watcher fires, an instruction to oppose.

The (system + summary + topic) prefix is intentionally stable so it can be
prompt-cached by adapters that support it.
"""

from __future__ import annotations

from dataclasses import dataclass

from pantheon.adapters.base import LLMMessage
from pantheon.anti_sycophancy import check_convergence
from pantheon.config import DiscussionConfig, LLMConfig
from pantheon.models import DiscussionState
from pantheon.prompts import (
    CHALLENGE_INJECTION,
    OPPOSITION_OVERRIDE,
    PARTICIPANT_BASE,
    POSITION_LABEL_INSTRUCTION,
    TURN_HEADER,
    format_utterance_for_context,
)


@dataclass
class BuiltContext:
    """Result of :func:`build_context`."""

    system_prompt: str
    history: list[LLMMessage]
    # Stable identifier for the cacheable prefix (system + summary + topic).
    # Adapters that support explicit caching key off this.
    cache_key: str
    # Diagnostic info for logs.
    convergence_triggered: bool
    window_used: int


def _format_recent_block(recent: list, max_chars: int = 4000) -> str:
    """Join recent utterances with a hard char cap to avoid prompt blow-ups."""
    parts: list[str] = []
    total = 0
    # Take from the end so the most recent context always survives.
    for utt in recent:
        chunk = format_utterance_for_context(utt)
        if total + len(chunk) > max_chars and parts:
            parts.insert(0, "[... earlier turns omitted ...]\n")
            break
        parts.insert(0, chunk)
        total += len(chunk)
    return "\n\n".join(parts) if parts else "(no prior utterances yet)"


def build_context(
    *,
    state: DiscussionState,
    speaker: LLMConfig,
    all_participants: list[LLMConfig],
    discussion_cfg: DiscussionConfig,
) -> BuiltContext:
    """Compose the system prompt + history for a given speaker's turn."""

    # ---- System prompt ----
    base = PARTICIPANT_BASE.format(
        display_name=speaker.display_name,
        topic=state.topic,
        n_participants=len(all_participants),
    )
    parts = [base]
    if discussion_cfg.anti_sycophancy.challenge_injection:
        parts.append(CHALLENGE_INJECTION)
    if discussion_cfg.anti_sycophancy.position_label_required:
        parts.append(POSITION_LABEL_INSTRUCTION)
    system_prompt = "".join(parts)

    # ---- Sliding window ----
    window_size = discussion_cfg.window_size_turns
    sliding_window = state.utterances[-window_size:]
    discussion_block = _format_recent_block(sliding_window)

    # ---- Summary block ----
    if state.summary:
        summary_block = f"\n\n[Earlier rounds, summarised]\n{state.summary}\n"
    else:
        summary_block = ""

    # ---- Injection block ----
    injection_block = ""
    if state.pending_injections:
        joined = "\n".join(f"- {inj}" for inj in state.pending_injections)
        injection_block = (
            f"\n\n[The human moderator (god) has injected the following "
            f"instruction(s) for this turn]\n{joined}"
        )

    # ---- Convergence override ----
    convergence = check_convergence(state.utterances, discussion_cfg.anti_sycophancy)
    if convergence.triggered:
        injection_block += OPPOSITION_OVERRIDE

    # ---- Turn header (the user message that triggers this turn) ----
    turn_header = TURN_HEADER.format(
        round_index=state.current_round + 1,
        max_rounds=discussion_cfg.max_rounds,
        display_name=speaker.display_name,
        discussion_block=discussion_block,
        summary_block=summary_block,
        injection_block=injection_block,
    )

    history: list[LLMMessage] = [LLMMessage(role="user", content=turn_header)]

    # Cache key: stable across turns where summary and topic haven't changed.
    cache_key = f"{speaker.name}:{hash((state.topic, state.summary))}"

    return BuiltContext(
        system_prompt=system_prompt,
        history=history,
        cache_key=cache_key,
        convergence_triggered=convergence.triggered,
        window_used=len(sliding_window),
    )
